[package]
name = "progresslib2-server-extension"
version = "0.1.0"
authors = ["nikita-skobov"]
edition = "2018"

[dependencies]
progresslib2 = { path = "../progresslib2" }
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.60"
actix-http = "2.2.0"
